- name: naginx install and run
  hosts: frontend
  tasks:
  - name: install nginx server
    ansible.builtin.package:
      name: nginx
      state: present
       
  - name: start nginx
    ansible.builtin.service:
      name: naginx
      state: started
      enabled: yes
      

