- name: varaiables from inventory
  hosts: local 
  connection: local
  tasks:
  - name: print couse information
    ansible.builtin.debug:
      msg: "Hello I am learning {{ COURSE }}, Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"