- name: varaiables from inventory
  hosts: frontend 
  tasks:
  - name: print couse information
    ansible.builtin.debug:
      msg: "Hello I am learning {{ COURSE }}, Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"