- name: understanding vars preferences
  hosts: local
  connection: local
  vars:
    GREETING: "Hello from Play"
  vars_files:
  - course.yaml
  vars_prompt:
  - name: GREETING
    prompt: please enter the GREETING
    private: false
  tasks:
  - name: print the greeting
    # vars:
    #   GREETING: "Hello from task"
    ansible.builtin.debug:
     msg: "{{ GREETING }}"